#!/bin/bash

#Configure PATH to SOAP binaries
BGISOAP_HOME=/usr/local/bgisoap
SOAP_HOME=$BGISOAP_HOME/soap
SOAP1_HOME=$SOAP_HOME/soap1/current
SOAP2_HOME=$SOAP_HOME/soap2/current
MSORT_HOME=$BGISOAP_HOME/msort/current
SOAP2SAM_HOME=$BGISOAP_HOME/soap2sam/current
SOAPDENOVO_HOME=$BGISOAP_HOME/soapdenovo/current
SOAPSPLICE_HOME=$BGISOAP_HOME/soapsplice/current
SOAPPOPINDEL_HOME=$BGISOAP_HOME/soappopindel/current
SOAPDENOVOTRANS_HOME=$BGISOAP_HOME/bgisoap/soapdenovotrans/current

PATH="$SOAPDENOVOTRANS_HOME/bin:$SOAPPOPINDEL_HOME/bin:$SOAPSPLICE_HOME/bin:$SOAPDENOVO_HOME/bin:$MSORT_HOME/bin:$SOAP2_HOME/bin:$SOAP1_HOME/bin:$PATH"

export SOAPDENOVOTRANS_HOME SOAPPOPINDEL_HOME SOAPSPLICE_HOME SOAPDENOVO_HOME SOAP2SAM_HOME MSORT_HOME SOAP2_HOME SOAP1_HOME BGISOAP_HOME SOAP_HOME PATH


