#!/bin/bash

#Configure PATH to SOAP binaries
BGISOAP_HOME=/usr/local/bgisoap
SOAP_HOME=$BGISOAP_HOME
SOAP1_HOME=$BGISOAP_HOME
SOAP2_HOME=$BGISOAP_HOME
MSORT_HOME=$BGISOAP_HOME
#SOAP2SAM_HOME=$BGISOAP_HOME
SOAPDENOVO1_HOME=$BGISOAP_HOME/soapdenovo1
SOAPSPLICE_HOME=$BGISOAP_HOME
SOAPPOPINDEL_HOME=$BGISOAP_HOME
SOAPDENOVOTRANS_HOME=$BGISOAP_HOME/soapdenovotrans
SOAPSNP_HOME=$BGISOAP_HOME
SOAPDENOVO2_HOME=$BGISOAP_HOME/soapdenovo2

PATH="$SOAPDENOVO2_HOME:$SOAPSNP_HOME:$SOAPDENOVOTRANS_HOME:$SOAPPOPINDEL_HOME:$SOAPSPLICE_HOME:$SOAPDENOVO1_HOME:$MSORT_HOME:$SOAP2_HOME:$SOAP1_HOME:$PATH:$BGISOAP_HOME"

export SOAPDENOVO2_HOME SOAPSNP_HOME SOAPDENOVOTRANS_HOME SOAPPOPINDEL_HOME SOAPSPLICE_HOME SOAPDENOVO1_HOME MSORT_HOME SOAP2_HOME SOAP1_HOME BGISOAP_HOME SOAP_HOME PATH


